using Domain.Entity;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Persistence.Seeding;

public static class Seeder
{
    public static void GenerateSeeds(ModelBuilder modelBuilder)
    {
        #region TicketStatusSeed

        modelBuilder.Entity<TicketStatus>().HasData(
            new TicketStatus
            {
                Color = "#256029",
                BackgroundColor = "#c8e6c9",
                Description = "Estado del ticket resuelto",
                Name = "Resuelto",
                CreatedBy = "AutoGenerated",
                Status = true,
                Id = new Guid("504731d4-0a34-41d5-9b0b-0611b3f76777"),
                CreatedOn = DateTime.Now, LastModifiedBy = "AutoGenerated", LastModifiedOn = new DateTime()
            }
        );

        #endregion
    }
}