#nullable disable

using Microsoft.EntityFrameworkCore.Migrations;

namespace Infrastructure.Migrations
{
    public partial class Seedingadded : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "LastModifiedBy",
                table: "UserRole",
                type: "NVARCHAR2(2000)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "NVARCHAR2(2000)");

            migrationBuilder.AlterColumn<string>(
                name: "LastModifiedBy",
                table: "User",
                type: "NVARCHAR2(2000)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "NVARCHAR2(2000)");

            migrationBuilder.AlterColumn<string>(
                name: "LastModifiedBy",
                table: "Ticket",
                type: "NVARCHAR2(2000)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "NVARCHAR2(2000)");

            migrationBuilder.AddColumn<Guid>(
                name: "GeneratedById",
                table: "Ticket",
                type: "RAW(16)",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AlterColumn<string>(
                name: "LastModifiedBy",
                table: "Role",
                type: "NVARCHAR2(2000)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "NVARCHAR2(2000)");

            migrationBuilder.AlterColumn<string>(
                name: "LastModifiedBy",
                table: "MenuItemRole",
                type: "NVARCHAR2(2000)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "NVARCHAR2(2000)");

            migrationBuilder.AlterColumn<string>(
                name: "LastModifiedBy",
                table: "MenuItem",
                type: "NVARCHAR2(2000)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "NVARCHAR2(2000)");

            migrationBuilder.InsertData(
                table: "MenuItem",
                columns: new[] { "Id", "CreatedBy", "CreatedOn", "Icon", "Label", "LastModifiedBy", "LastModifiedOn", "Order", "RouterLink" },
                values: new object[,]
                {
                    { new Guid("012fff70-84e2-4962-84a3-3b7833bb71fb"), "AutoGenerated", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "fa-solid fa-house", "Inicio", null, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), 0, "home" },
                    { new Guid("504731d4-0a34-41d5-9b0b-0611b3f76096"), "AutoGenerated", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "fa-solid fa-plane-departure", "Tickets", null, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), 1, "tickets" }
                });

            migrationBuilder.InsertData(
                table: "Role",
                columns: new[] { "Id", "CreatedBy", "CreatedOn", "LastModifiedBy", "LastModifiedOn", "RoleName" },
                values: new object[,]
                {
                    { new Guid("4a77cee4-5cfa-4c90-b41a-08da36159111"), "AutoGenerated", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), null, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "User" },
                    { new Guid("bf1de1aa-fc78-4b92-6942-08da36131198"), "AutoGenerated", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), null, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Admin" }
                });

            migrationBuilder.InsertData(
                table: "User",
                columns: new[] { "Id", "CreatedBy", "CreatedOn", "LastModifiedBy", "LastModifiedOn", "Name", "Password", "Username" },
                values: new object[,]
                {
                    { new Guid("4a77cee4-5cfa-4c90-b41a-08da36159120"), "AutoGenerated", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), null, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Kevin Pontón", "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918", "Admin" },
                    { new Guid("c82a18c6-e473-4976-5f2e-08da35e4eb6f"), "AutoGenerated", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), null, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Usuario", "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4", "User" }
                });

            migrationBuilder.InsertData(
                table: "MenuItemRole",
                columns: new[] { "MenuItemId", "RoleId", "CreatedBy", "CreatedOn", "Id", "LastModifiedBy", "LastModifiedOn" },
                values: new object[,]
                {
                    { new Guid("012fff70-84e2-4962-84a3-3b7833bb71fb"), new Guid("4a77cee4-5cfa-4c90-b41a-08da36159111"), "AutoGenerated", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new Guid("c82a18c6-e473-4976-5f2e-08da35e4eb8b"), null, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                    { new Guid("504731d4-0a34-41d5-9b0b-0611b3f76096"), new Guid("4a77cee4-5cfa-4c90-b41a-08da36159111"), "AutoGenerated", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new Guid("c82a18c6-e473-4976-5f2e-08da35e4eb8a"), null, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                    { new Guid("012fff70-84e2-4962-84a3-3b7833bb71fb"), new Guid("bf1de1aa-fc78-4b92-6942-08da36131198"), "AutoGenerated", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new Guid("c82a18c6-e473-4976-5f2e-08da35e4eb8e"), null, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                    { new Guid("504731d4-0a34-41d5-9b0b-0611b3f76096"), new Guid("bf1de1aa-fc78-4b92-6942-08da36131198"), "AutoGenerated", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new Guid("c82a18c6-e473-4976-5f2e-08da35e4ebfe"), null, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) }
                });

            migrationBuilder.InsertData(
                table: "UserRole",
                columns: new[] { "RoleId", "UserId", "CreatedBy", "CreatedOn", "Id", "LastModifiedBy", "LastModifiedOn" },
                values: new object[,]
                {
                    { new Guid("4a77cee4-5cfa-4c90-b41a-08da36159111"), new Guid("c82a18c6-e473-4976-5f2e-08da35e4eb6f"), "AutoGenerated", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new Guid("bf1de1aa-fc78-4b92-6942-09da3e131298"), null, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                    { new Guid("bf1de1aa-fc78-4b92-6942-08da36131198"), new Guid("4a77cee4-5cfa-4c90-b41a-08da36159120"), "AutoGenerated", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new Guid("bf1de1aa-fc78-4b92-6942-09da36131298"), null, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Ticket_GeneratedById",
                table: "Ticket",
                column: "GeneratedById");

            migrationBuilder.AddForeignKey(
                name: "FK_Ticket_User_GeneratedById",
                table: "Ticket",
                column: "GeneratedById",
                principalTable: "User",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Ticket_User_GeneratedById",
                table: "Ticket");

            migrationBuilder.DropIndex(
                name: "IX_Ticket_GeneratedById",
                table: "Ticket");

            migrationBuilder.DeleteData(
                table: "MenuItemRole",
                keyColumns: new[] { "MenuItemId", "RoleId" },
                keyValues: new object[] { new Guid("012fff70-84e2-4962-84a3-3b7833bb71fb"), new Guid("4a77cee4-5cfa-4c90-b41a-08da36159111") });

            migrationBuilder.DeleteData(
                table: "MenuItemRole",
                keyColumns: new[] { "MenuItemId", "RoleId" },
                keyValues: new object[] { new Guid("504731d4-0a34-41d5-9b0b-0611b3f76096"), new Guid("4a77cee4-5cfa-4c90-b41a-08da36159111") });

            migrationBuilder.DeleteData(
                table: "MenuItemRole",
                keyColumns: new[] { "MenuItemId", "RoleId" },
                keyValues: new object[] { new Guid("012fff70-84e2-4962-84a3-3b7833bb71fb"), new Guid("bf1de1aa-fc78-4b92-6942-08da36131198") });

            migrationBuilder.DeleteData(
                table: "MenuItemRole",
                keyColumns: new[] { "MenuItemId", "RoleId" },
                keyValues: new object[] { new Guid("504731d4-0a34-41d5-9b0b-0611b3f76096"), new Guid("bf1de1aa-fc78-4b92-6942-08da36131198") });

            migrationBuilder.DeleteData(
                table: "UserRole",
                keyColumns: new[] { "RoleId", "UserId" },
                keyValues: new object[] { new Guid("4a77cee4-5cfa-4c90-b41a-08da36159111"), new Guid("c82a18c6-e473-4976-5f2e-08da35e4eb6f") });

            migrationBuilder.DeleteData(
                table: "UserRole",
                keyColumns: new[] { "RoleId", "UserId" },
                keyValues: new object[] { new Guid("bf1de1aa-fc78-4b92-6942-08da36131198"), new Guid("4a77cee4-5cfa-4c90-b41a-08da36159120") });

            migrationBuilder.DeleteData(
                table: "MenuItem",
                keyColumn: "Id",
                keyValue: new Guid("012fff70-84e2-4962-84a3-3b7833bb71fb"));

            migrationBuilder.DeleteData(
                table: "MenuItem",
                keyColumn: "Id",
                keyValue: new Guid("504731d4-0a34-41d5-9b0b-0611b3f76096"));

            migrationBuilder.DeleteData(
                table: "Role",
                keyColumn: "Id",
                keyValue: new Guid("4a77cee4-5cfa-4c90-b41a-08da36159111"));

            migrationBuilder.DeleteData(
                table: "Role",
                keyColumn: "Id",
                keyValue: new Guid("bf1de1aa-fc78-4b92-6942-08da36131198"));

            migrationBuilder.DeleteData(
                table: "User",
                keyColumn: "Id",
                keyValue: new Guid("4a77cee4-5cfa-4c90-b41a-08da36159120"));

            migrationBuilder.DeleteData(
                table: "User",
                keyColumn: "Id",
                keyValue: new Guid("c82a18c6-e473-4976-5f2e-08da35e4eb6f"));

            migrationBuilder.DropColumn(
                name: "GeneratedById",
                table: "Ticket");

            migrationBuilder.AlterColumn<string>(
                name: "LastModifiedBy",
                table: "UserRole",
                type: "NVARCHAR2(2000)",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "NVARCHAR2(2000)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "LastModifiedBy",
                table: "User",
                type: "NVARCHAR2(2000)",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "NVARCHAR2(2000)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "LastModifiedBy",
                table: "Ticket",
                type: "NVARCHAR2(2000)",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "NVARCHAR2(2000)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "LastModifiedBy",
                table: "Role",
                type: "NVARCHAR2(2000)",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "NVARCHAR2(2000)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "LastModifiedBy",
                table: "MenuItemRole",
                type: "NVARCHAR2(2000)",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "NVARCHAR2(2000)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "LastModifiedBy",
                table: "MenuItem",
                type: "NVARCHAR2(2000)",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "NVARCHAR2(2000)",
                oldNullable: true);
        }
    }
}
